config/routes.rb
Rails.application.routes.draw do
  resources :users

  root 'static_pages#home'

  get 'about' => 'static_pages#about'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :user_events
  has_many :users, through: :user_events
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true

  has_many :user_events
  has_many :events, :through => :user_events

  has_secure_password
end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email / password combination'
      render 'sessions/new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = 'High Five! You successfully signed up'
      redirect_to @user
    else
      render 'users/new'
    end
  end

  def destroy
  end

  def update
  end

  def edit
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user?(user)
    user == current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <!-- Brand Logo -->
    <div class="navbar-header">
      <%= link_to 'Private Events', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if logged_in? %>
            <li class="dropdown">
              <a href='#' class='dropdown-toggle' data-toggle='dropdown'>
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Profile', current_user %></li>
                <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
                <li class='divider'></li>
                <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
              </ul>
            </li>
        <% else %>
            <%= link_to 'Sign In', login_path, class: 'btn btn-primary navbar-btn' %>
            <%= link_to 'Sign Up', new_user_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PrivateEvents</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
    <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, 'error') %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>This will be my about page</h1>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Private Events</h1>
  <p>Click here if you want to create and invite users to your events!</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Sign Up</a></p>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.erb
<% @users.each do |user| %>
    <%= user.name %> | <%= user.email %> <br>
<% end %>

app/views/users/new.html.erb
<h3>Great! You are only one step away from joining the Private Events!</h3>
<div class="col-md-offset-2">
  <div class="form-group">
    <div class="form-horizontal">
      <%= form_for @user do |f| %>
          <%= render 'shared/error_messages', object: f.object %>

          <div class="form-group">
            <%= f.label :name, class: 'col-sm-2 control-label' %>
            <div class="col-sm-6">
              <%= f.text_field :name, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :email, class: 'col-sm-2 control-label' %>
            <div class="col-sm-6">
              <%= f.text_field :email, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password, class: 'col-sm-2 control-label' %>
            <div class="col-sm-6">
              <%= f.password_field :password, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, class: 'col-sm-2 control-label' %>
            <div class="col-sm-6">
              <%= f.password_field :password_confirmation, class: 'form-control' %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <%= f.submit 'Sign Up', class: 'btn btn-default' %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.erb
<div class="row">
  <div class="col-sm-2 col-sm-offset-2">
    <h1><%= @user.name %></h1>
  </div>

  <div class="col-sm-6">
    <% if @user.events.any? %>
        <% @user.events.each do |event| %>
            <%= event.id %> | <%= event.description %> <br>
        <% end %>
    <% end %>
  </div>
</div>